### ISSUE TITLE
Why does getContent take a url and not a name?

### ISSUE THREAD

**Issue by mattpage** [flightstats/node-datahub#12]
Most of the "public" methods on node-datahub build a url given a channel name.
getContent takes a channelUrl? This seems out of place.

```
Datahub.prototype.getContent = function(channelUrl){
  if (!channelUrl){
    throw new Error('Missing channel URL');
  }

  return this._crud(this.config.url + channelUrl, 'GET');
};
```
```
Datahub.prototype.getStatus = function(name){
  if (!name){
    throw new Error('Missing channel name');
  }

  return this._crud(this.config.url + '/channel/' + name + '/status', 'GET');
};
```

**Comment by cmwood** [comment]
There is a need to use a fully qualified URL in some cases, specifically on callbacks where the URIs represent GETs on a different channel altogether. That is why getContent was written this way. Both are needed it seems.

**Comment by mattpage** [comment]
Hmm... we could expose the _crud method for such purposes.
Is the need for fully qualified url hypothetical or was this a breaking change?

**Comment by cmwood** [comment]
True. The _crud method could be used in this case. The latest change is a breaking change if the module were published.

**Comment by mattpage** [comment]
we could also create a getContentByUrl, which feels a bit icky. Or we could parse the incoming value using require('url').parse but that seems a bit iffy.

**Comment by mattpage** [comment]
I suppose getContentByUrl isn't too terrible. It's essentially a wrapper around _crud.
I defer to you @cmwood, since I suspect the last commit broke your client.

**Comment by cmwood** [comment]
Meh. Actually, fetching content off v2 of the hub requires not only the name of the channel but also an id. Since this client's constructor requires the hub's 'base' url (http://hubhost) the following example would be an acceptable parameter to the getContent method : 'someChannelName/2013/04/23/20/42/31/749/{hash}'

Or, we could pass two parameters; channel name and the id.

Either way, a method that takes fully qualified URL is not needed.
